### ISSUE TITLE
Discovery is broken

### ISSUE THREAD

**Issue by indexzero** [vesln/package#1]
A module caching in a complex dependency tree will cause `.discover` to behave inappropriately.

**Comment by vesln** [comment]
I hadn't thought about it until now. I've just pushed a new version with a fix. Thank you.

**Comment by indexzero** [comment]
@vesln Bingo. Your fix in ad186945d277dd04abfa6e4b469cc55733936394 is also how pkginfo works. I learned this one the hard way a few months back.

**Comment by vesln** [comment]
Yeah. I guess module caching is really confusing sometimes. Thanks once again.
