### ISSUE TITLE
obsolete?

### ISSUE THREAD

**Issue by dodo** [vesln/package#2]
for node >=0.5 this is exaclty the same:

``` javascript
require('./package.json')
require('word/package.json')
```

:)

**Comment by vesln** [comment]
Yeah. Do not use this module. Back then I thought it's a good idea, but it's just another useless dependency. As soon as I find some free time I will remove it from my modules.

**Comment by vesln** [comment]
require('./package.json').version is way more expressive :)

**Comment by isaacs** [comment]
If you want to get _all_ the semantics that npm uses when loading package.json files (including loading from comments in a js file, pulling in the readme, checking for misspellings, etc.) then use the [read-package-json](https://github.com/isaacs/read-package-json) module.

**Comment by vesln** [comment]
@isaacs Awesome! I just put deprecation notice in the readme file.
